Financiera_KeniaMoreira/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app_seguridad import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('fina/', include('app_financiera.urls')),
    path('login/', views.log_in, name="login_view"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_financiera/urls.py
from django.urls import path
from . import views

app_name = 'fina'

urlpatterns = [
    path('', views.index, name="index"),
    path('deposito/', views.deposito, name="deposito"),
    path('retiro/', views.retiro, name="retiro"),
    path('transferencia/', views.transferencia, name="transferencia"),
]

app_financiera/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Cliente(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    direccion = models.TextField()
    fecha_nacimiento = models.DateField()
    telefono = models.IntegerField()
    correo = models.EmailField(null=True, blank=True)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class CuentaBancaria(models.Model):
    ESTADOS=(
        ('1', 'Activa'),
        ('2', 'Inactiva')
    )
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=1, choices=ESTADOS, default='1')
    saldo = models.DecimalField(max_digits=10, decimal_places=2)
    propietario = models.OneToOneField(Cliente, blank=True, on_delete=models.CASCADE, primary_key=True,)

    def __str__(self):
        return self.estado

class Deposito(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    monto_depositado = models.DecimalField(max_digits=10, decimal_places=2)
    

class Retiro(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    monto_retirado = models.DecimalField(max_digits=10, decimal_places=2)
    monto = models.DecimalField(max_digits=10, decimal_places=2)

    @property
    def monto_total(self):
        monto_final = self.cuentabancaria_set.count()
        return self.monto - monto_final #con self accedemos a los campos 

class Transferencia(models.Model):
    cuenta_origen = models.CharField(max_length=40)
    cuenta_destino = models.CharField(max_length=40)
    fecha_transferencia = models.DateTimeField(auto_now_add=True)
    monto_depositar = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion_transferencia = models.TextField()

    def __str__(self):
        return self.cuenta_destino

class Transacciones(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    deposito = models.ForeignKey(Deposito, on_delete=models.CASCADE)
    retiro = models.ForeignKey(Retiro, on_delete=models.CASCADE)
    transferencia = models.ForeignKey(Transferencia, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

app_seguridad/models.py
from django.db import models

# Create your models here.

app_financiera/views.py
from django.shortcuts import render
from .models import Deposito, Retiro, Transferencia

# Create your views here.
def index(request):
    return render(request, 'app_financiera/index.html')

def deposito(request):
    if request.method == 'POST':
        nombre  = request.POST.get('nombre')
        apellido  = request.POST.get('apellido')
        monto_depositado = request.POST.get('monto_depositado')

        p = Deposito(
            nombre = nombre, 
            apellido = apellido, 
            monto_depositado = monto_depositado
            )
        p.save()
        
    activo= 'deposito'

    data = Deposito.objects.all().order_by('nombre')

    ctx = {
        'activo':activo,
        'formulario': data
    }

    return render(request, 'app_financiera/depositos.html', ctx)
    

def retiro(request):
    if request.method == 'POST':
        nombre  = request.POST.get('nombre')
        apellido  = request.POST.get('apellido')
        monto_retirado = request.POST.get('monto_retirado')
        monto = request.POST.get('monto')

        p = Retiro(
            nombre = nombre, 
            apellido = apellido, 
            monto_retirado = monto_retirado,
            monto = monto
            )
        p.save()
        
    activo= 'deposito'

    data = Retiro.objects.all().order_by('nombre')

    ctx = {
        'activo':activo,
        'formulario': data
    }

    return render(request, 'app_financiera/retiros.html', ctx)

def transferencia(request):
    if request.method == 'POST':
        cuenta_origen  = request.POST.get('cuenta_origen')
        cuenta_destino  = request.POST.get('cuenta_destino')
        monto_depositar = request.POST.get('monto_depositar')
        descripcion_trasferencia = request.POST.get('descripcion_transferencia')

        p = Transferencia(
            cuenta_origen = cuenta_origen, 
            cuenta_destino = cuenta_destino, 
            monto_depositar = monto_depositar,
            descripcion_trasferencia = descripcion_trasferencia
            )
        p.save()
        
    activo= 'transferencia'

    data = Transferencia.objects.all().order_by('cuenta_origen')

    ctx = {
        'activo':activo,
        'formulario': data
    }

    return render(request, 'app_financiera/transferencias.html', ctx)

app_seguridad/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login

# Create your views here.

def index(request):
    return render(request, 'app_seguridad/index.html')

def log_in(request):
    if request.method == 'POST':
        username = request.POST.get('usuario')
        password = request.POST.get('contrasena')

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                return HttpResponse('existe activo')
            else: 
                return HttpResponse('existe pero no activo')
        else:
            return HttpResponse('No existe')

        return HttpResponse(f'Usuario: {username} - Clave: {password}')
    else:
        return redirect('/')

app_financiera/templates/app_financiera/depositos.html
{% extends "base.html" %}

{% block title %}
    Depositos
{% endblock %}

{% block container %}
    <div class="row">
        <!-- formulario -->
        <div class="col-3">
                <form action="{% url 'fina:deposito' %}" method="post">
                    {% csrf_token %}
                    <div class="mb-2">
                        <label for="nombre">Nombre</label>
                        <input type="text" value="{{ p.nombre }}" name="nombre" id="nombre" class="form-control">
                    </div>
                    <div class="mb-2">
                        <label for="apellido">Apellido</label>
                        <input type="text" value="{{ p.apellido }}" name="apellido" id="apellido" class="form-control">
                    </div>
                    <div class="mb-2">
                        <label for="monto">Monto a depositar</label>
                        <input type="text" value="{{ p.monto_depositado }}" name="monto_depositado" id="monto_depositado" class="form-control">
                    </div>
                    <div class="mb-2">
                        <input type ="submit" class="btn btn-success" value="Registrar Deposito">
                    </div>
            </form>
        </div>
        <!-- datos -->
        <div class="col-9">
             <h2 class= "mt-3">Lista de Depositos {{ formulario.count }}</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Monto Depositado</th>
                        <th>Monto Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in formulario %}
                        <tr>
                            <td>{{ p.nombre }}</td>
                            <td>{{ p.apellido }}</td>
                            <td>{{ p.monto_depositado }}</td>
                            <td>{{ p.monto_total }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app_financiera/templates/app_financiera/index.html
{% extends "base.html" %}

{% block title %}
    Index
{% endblock %}

{% block container %}
    <h1>Hola</h1>
{% endblock %}

app_financiera/templates/app_financiera/retiros.html
{% extends "base.html" %}

{% block title %}
    Depositos
{% endblock %}

{% block container %}
    <div class="row">
        <!-- formulario -->
        <div class="col-3">
                {% csrf_token %}
                <div class="mb-2">
                    <label for="nombre">Nombre</label>
                    <input type="text" name="nombre" id="nombre" class="form-control">
                </div>
                <div class="mb-2">
                    <label for="apellido">Apellido</label>
                    <input type="text" name="apellido" id="apellido" class="form-control">
                </div>
                <div class="mb-2">
                    <label for="monto">Monto a Retirar</label>
                    <input type="text"  name="monto" id="monto" class="form-control">
                </div>
                <div class="mb-2">
                    <input type ="submit" class="btn btn-success" value="Retirar">
                </div>
            </form>
        </div>
        <!-- datos -->
        <div class="col-9">
             <h2 class= "mt-3">Lista de Retiros {{ formulario.count }}</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Monto Retirado</th>
                        <th>Monto Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in formulario %}
                        <tr>
                            <td>{{ p.nombre }}</td>
                            <td>{{ p.apellido }}</td>
                            <td>{{ p.monto_retirado }}</td>
                            <td>{{ p.monto }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app_financiera/templates/app_financiera/transferencias.html
{% extends "base.html" %}

{% block title %}
    Transferencias
{% endblock %}

{% block container %}
    <div class="row">
        <!-- formulario -->
        <div class="col-3">
                {% csrf_token %}
                <div class="mb-2">
                    <label for="cuentaOrigen">Cuenta Origen</label>
                    <input type="text" name="cuentaOrigen" id="cuentaOrigen" class="form-control">
                </div>
                <div class="mb-2">
                    <label for="apellido">Cuenta Destino</label>
                    <input type="text" name="apellido" id="apellido" class="form-control">
                </div>
                <div class="mb-2">
                    <label for="monto">Monto a Transferir</label>
                    <input type="text"  name="monto" id="monto" class="form-control">
                </div>
                <div class="mb-2">
                    <label for="monto">Descripcion Transferencia</label>
                    <input type="text"  name="monto" id="monto" class="form-control">
                </div>
                <div class="mb-2">
                    <input type ="submit" class="btn btn-success" value="Retirar">
                </div>
            </form>
        </div>
        <!-- datos -->
        <div class="col-9">
             <h2 class= "mt-3">Lista de Transferencias {{ formulario.count }}</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Cuenta Origen</th>
                        <th>Cuenta Destino</th>
                        <th>Monto Transferido</th>
                        <th>Descripcion</th>
                        <th>Fecha</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in formulario %}
                        <tr>
                            <td>{{ p.cuenta_origen }}</td>
                            <td>{{ p.cuenta_destino }}</td>
                            <td>{{ p.monto_depositar }}</td>
                            <td>{{ p.descripcion_transferencia }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app_seguridad/templates/app_seguridad/index.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.84.0">
        <title>Signin Template · Bootstrap v5.0</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
        <!-- Bootstrap core CSS -->
        <link href="{% static 'conferencia/bootstrap/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'conferencia/css/signin.css' %}" rel="stylesheet" >

        <!-- Favicons -->
        <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
        <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
        <meta name="theme-color" content="#7952b3">

        <style>
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
        }

        @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
        }
        </style>


        <!-- Custom styles for this template -->
        <link href="signin.css" rel="stylesheet">
    </head>
    <body class="text-center">

        <main class="form-signin">
            <form action="{% url 'login_view' %}" method="post">
                {% csrf_token %}
                <img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
                <h1 class="h3 mb-3 fw-normal">Inicia sesion aqui</h1>

                <div class="form-floating">
                    <input name="usuario" type="text" class="form-control" id="floatingInput" placeholder="Nombre de usuario">
                    <label for="floatingInput">Usuario</label>
                </div>
                <div class="form-floating">
                    <input name="contrasena" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Contraseña</label>
                </div>
                <div class="checkbox mb-3">
                    <label>
                    <input type="checkbox" value="remember-me"> Recordarme
                    </label>
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Iniciar Sesion</button>
                <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
            </form>
        </main>
    </body>
</html>